[profiles.weathervane_orchestrator]
base_instructions = "/Volumes/BigSSD4/nathanielschmiedehaus/Documents/WeatherVane/docs/wvo_prompt.md"
model = "gpt-5-codex"
sandbox = "danger-full-access"
approval = "never"
reasoning = "auto"
include_plan_tool = true
cwd = "/Volumes/BigSSD4/nathanielschmiedehaus/Documents/WeatherVane"

[projects."/Volumes/BigSSD4/nathanielschmiedehaus/Documents/WeatherVane"]
trust_level = "trusted"

[mcp_servers.weathervane]
command = "node"
args = ["tools/wvo_mcp/dist/index.js", "--workspace", "/Volumes/BigSSD4/nathanielschmiedehaus/Documents/WeatherVane"]
