version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: npm run dev --prefix apps/web
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: python -m apps.worker.run
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: weathervane
      POSTGRES_PASSWORD: weathervane
      POSTGRES_DB: weathervane
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
