import type { DashboardResponse } from "../types/dashboard";

function iso(date: Date): string {
  return date.toISOString();
}

export function buildDemoDashboard(now: Date = new Date()): DashboardResponse {
  const generatedAt = new Date(now);
  generatedAt.setMilliseconds(0);
  const midnight = new Date(generatedAt);
  midnight.setHours(0, 0, 0, 0);

  const offsets = Array.from({ length: 12 }, (_, idx) => idx);
  const baseSeries = offsets.map((idx) => 92 + Math.sin(idx / 2) * 3);
  const coverageEndDate = iso(midnight).slice(0, 10);

  return {
    tenant_id: "demo-tenant",
    generated_at: iso(generatedAt),
    guardrails: [
      {
        name: "Budget adherence",
        status: "healthy",
        value: 94.2,
        target: 90,
        unit: "pct",
        delta_pct: 2.4,
        notes: "Daily cap holding steady across channels.",
      },
      {
        name: "ROAS floor",
        status: "watch",
        value: 3.1,
        target: 3,
        unit: "ratio",
        delta_pct: -0.8,
        notes: "Meta creative fatigue pushing ROAS towards floor.",
      },
      {
        name: "CPA ceiling",
        status: "breach",
        value: 54.5,
        target: 50,
        unit: "usd",
        delta_pct: 6.9,
        notes: "Automation engine paused for Apparel South due to storm drag.",
      },
    ],
    spend_trackers: [
      {
        name: "Meta Spend",
        channel: "Paid Social",
        value: 42500,
        change_pct: 5.2,
        target: 43000,
        unit: "usd",
        sparkline: baseSeries,
      },
      {
        name: "Google Revenue",
        channel: "Paid Search",
        value: 132000,
        change_pct: 3.6,
        target: 128000,
        unit: "usd",
        sparkline: offsets.map((idx) => 98 + Math.sin(idx / 1.7) * 4),
      },
      {
        name: "Email Contribution",
        channel: "Lifecycle",
        value: 24000,
        change_pct: -1.5,
        target: 23500,
        unit: "usd",
        sparkline: offsets.map((idx) => 88 + Math.sin(idx / 1.3) * 2.5),
      },
    ],
    weather_events: [
      {
        id: "storm-midwest",
        title: "Severe storm window",
        description: "Cold front with hail risk across Chicago and Detroit markets.",
        severity: "high",
        geo_region: "Midwest USA",
        starts_at: iso(new Date(midnight.getTime() + 6 * 60 * 60 * 1000)),
        ends_at: iso(new Date(midnight.getTime() + 18 * 60 * 60 * 1000)),
        latitude: 41.8781,
        longitude: -87.6298,
        weather_type: "hail",
      },
      {
        id: "heatwave-south",
        title: "Heat surge boosting demand",
        description: "Apparel conversions trending +12% in Austin & Dallas.",
        severity: "medium",
        geo_region: "Texas",
        starts_at: iso(new Date(midnight.getTime() - 12 * 60 * 60 * 1000)),
        ends_at: iso(new Date(midnight.getTime() + 12 * 60 * 60 * 1000)),
        latitude: 30.2672,
        longitude: -97.7431,
        weather_type: "heatwave",
      },
      {
        id: "marine-layer",
        title: "Marine layer dampening store visits",
        description: "Expect slower coastal traffic until the marine layer clears.",
        severity: "low",
        geo_region: "SoCal Coast",
        starts_at: iso(midnight),
        ends_at: iso(new Date(midnight.getTime() + 9 * 60 * 60 * 1000)),
        latitude: 34.0195,
        longitude: -118.4912,
        weather_type: "fog",
      },
    ],
    automation: [
      {
        name: "Assist Guardrails",
        uptime_pct: 99.4,
        incidents_7d: 1,
        last_incident_at: iso(new Date(generatedAt.getTime() - 14 * 60 * 60 * 1000)),
        status: "normal",
        notes: "Operator acknowledged CPA drift within SLA.",
      },
      {
        name: "Automation engine Execution",
        uptime_pct: 96.8,
        incidents_7d: 2,
        last_incident_at: iso(new Date(generatedAt.getTime() - 6 * 60 * 60 * 1000)),
        status: "degraded",
        notes: "Paused Apparel South while storm response recalibrates.",
      },
    ],
    data_coverage: {
      tenant_id: "demo-tenant",
      window_days: 90,
      end_date: coverageEndDate,
      generated_at: iso(generatedAt),
      status: "warning",
      buckets: {
        sales: {
          name: "sales",
          status: "ok",
          observed_days: 90,
          window_days: 90,
          coverage_ratio: 1,
          latest_date: coverageEndDate,
          sources: ["storage/lake/raw/demo-tenant_shopify_orders"],
          issues: [],
          extra_metrics: {
            latest_created_at: coverageEndDate,
          },
        },
        spend: {
          name: "spend",
          status: "warning",
          observed_days: 82,
          window_days: 90,
          coverage_ratio: 0.91,
          latest_date: coverageEndDate,
          sources: [
            "storage/lake/raw/demo-tenant_meta_ads",
            "storage/lake/raw/demo-tenant_google_ads",
          ],
          issues: ["Meta Ads missing 3 days in the trailing window."],
          extra_metrics: {
            latest_observation: coverageEndDate,
            source_count: 2,
          },
        },
        weather: {
          name: "weather",
          status: "ok",
          observed_days: 88,
          window_days: 90,
          coverage_ratio: 0.98,
          latest_date: coverageEndDate,
          sources: ["experiments/features/weather_join_validation.json"],
          issues: [],
          extra_metrics: {
            geocoded_order_ratio: 0.9,
            missing_dates: [],
          },
        },
      },
    },
    ingestion: [
      {
        name: "Shopify",
        source: "Commerce",
        status: "healthy",
        lag_minutes: 4,
        sla_minutes: 10,
        last_synced_at: iso(new Date(generatedAt.getTime() - 4 * 60 * 1000)),
        notes: "Webhooks flowing normally.",
      },
      {
        name: "Meta Ads",
        source: "Paid Social",
        status: "delayed",
        lag_minutes: 28,
        sla_minutes: 15,
        last_synced_at: iso(new Date(generatedAt.getTime() - 28 * 60 * 1000)),
        notes: "Rate limiting triggered; retry backoff active.",
      },
      {
        name: "Google Ads",
        source: "Paid Search",
        status: "syncing",
        lag_minutes: 12,
        sla_minutes: 20,
        last_synced_at: iso(new Date(generatedAt.getTime() - 12 * 60 * 1000)),
        notes: "Sync resumed after nightly window.",
      },
    ],
    alerts: [
      {
        id: "alert-apparel-south",
        title: "CPA breach: Apparel South",
        detail: "Automation engine paused pushes while CPA exceeds $50 ceiling.",
        severity: "critical",
        occurred_at: iso(new Date(generatedAt.getTime() - 35 * 60 * 1000)),
        acknowledged: false,
        escalated_to: "On-call Operator",
        escalated_at: iso(new Date(generatedAt.getTime() - 32 * 60 * 1000)),
        escalation_channel: "slack",
        related_objects: ["campaign:apparel-south", "guardrail:cpa"],
      },
      {
        id: "alert-meta-rate",
        title: "Meta rate limiting",
        detail: "Meta Ads connector backing off; expect refreshed metrics in 15 minutes.",
        severity: "warning",
        occurred_at: iso(new Date(generatedAt.getTime() - 70 * 60 * 1000)),
        acknowledged: true,
        acknowledged_at: iso(new Date(generatedAt.getTime() - 60 * 60 * 1000)),
        escalated_to: null,
        related_objects: ["connector:meta"],
      },
      {
        id: "alert-weather-brief",
        title: "Brief: Midwest hail window",
        detail: "Share scenario with Priya so promo caps adjust before storm hits.",
        severity: "info",
        occurred_at: iso(new Date(generatedAt.getTime() - 2 * 60 * 60 * 1000)),
        acknowledged: false,
        escalated_to: null,
        related_objects: ["scenario:midwest-hail"],
      },
    ],
    allocator: {
      run_id: "allocator-demo",
      generated_at: iso(generatedAt),
      mode: "assist",
      total_spend: 250000,
      total_spend_delta: -33000,
      total_spend_delta_pct: -11.6,
      guardrail_breaches: 1,
      notes: ["Demo allocator recommendations seeded from fallback telemetry."],
      recommendations: [
        {
          platform: "Meta",
          spend_delta: -15000,
          spend_delta_pct: -12,
          spend_after: 110000,
          severity: "critical",
          guardrail_count: 1,
          top_guardrail: "CPA breach detected",
          notes: null,
        },
        {
          platform: "Google",
          spend_delta: -8000,
          spend_delta_pct: -6,
          spend_after: 140000,
          severity: "warning",
          guardrail_count: 1,
          top_guardrail: "Budget delta exceeds policy",
          notes: null,
        },
        {
          platform: "Email",
          spend_delta: 2000,
          spend_delta_pct: 5,
          spend_after: 30000,
          severity: "info",
          guardrail_count: 0,
          top_guardrail: null,
          notes: null,
        },
      ],
    },
    weather_kpis: [
      {
        id: "high_risk_alerts",
        label: "High-risk alerts",
        value: 2,
        unit: "count",
        delta_pct: 12.5,
        sparkline: [1, 2, 3, 2.5, 3.5],
        description: "2 of 3 active weather windows carry high-risk severity.",
      },
      {
        id: "regions_impacted",
        label: "Regions impacted",
        value: 3,
        unit: "count",
        delta_pct: null,
        sparkline: [1, 2, 3],
        description: "Midwest, Texas, and SoCal regions reporting weather signals.",
      },
      {
        id: "next_event_lead_time",
        label: "Lead time to next event",
        value: 4,
        unit: "hours",
        delta_pct: null,
        sparkline: [4],
        description: "Next weather window begins in roughly four hours.",
      },
    ],
    suggestion_telemetry: [
      {
        signature: "Gulf Coast|High-risk weather events incoming.|2025-05-01T14:00:00Z|2|3",
        region: "Gulf Coast",
        reason: "High-risk conditions detected. Next event in 2 hours. 2 high-risk alerts in queue.",
        view_count: 54,
        focus_count: 19,
        dismiss_count: 6,
        high_risk_count: 2,
        event_count: 3,
        focus_rate: 19 / 54,
        dismiss_rate: 6 / 54,
        engagement_rate: (19 + 6) / 54,
        has_scheduled_start: true,
        next_event_starts_at: iso(new Date(midnight.getTime() + 16 * 60 * 60 * 1000)),
        first_occurred_at: iso(new Date(generatedAt.getTime() - 36 * 60 * 60 * 1000)),
        last_occurred_at: iso(new Date(generatedAt.getTime() - 60 * 60 * 1000)),
        tenants: ["demo-tenant"],
        severities: ["high"],
        viewport_breakpoints: ["desktop", "tablet"],
        metadata: {
          layoutVariant: "dense",
          ctaShown: true,
          regionSlug: "gulf-coast",
          suggestionSummary: "3 events · 2 high-risk alerts · Next starts in 2 hours",
          regionSummary: "3 events · 2 high-risk alerts · Next starts in 2 hours",
          tenantMode: "demo",
          guardrailStatus: "watch",
          criticalAlertCount: 3,
          signature: "Gulf Coast|High-risk weather events incoming.|2025-05-01T14:00:00Z|2|3",
        },
      },
      {
        signature: "Pacific Northwest|Monitoring heavy rain bands.|2025-05-02T08:00:00Z|1|1",
        region: "Pacific Northwest",
        reason: "Monitoring heavy rain bands; shift spend to insulated regions.",
        view_count: 31,
        focus_count: 11,
        dismiss_count: 4,
        high_risk_count: 1,
        event_count: 1,
        focus_rate: 11 / 31,
        dismiss_rate: 4 / 31,
        engagement_rate: (11 + 4) / 31,
        has_scheduled_start: true,
        next_event_starts_at: iso(new Date(midnight.getTime() + 32 * 60 * 60 * 1000)),
        first_occurred_at: iso(new Date(generatedAt.getTime() - 48 * 60 * 60 * 1000)),
        last_occurred_at: iso(new Date(generatedAt.getTime() - 5 * 60 * 60 * 1000)),
        tenants: ["demo-tenant"],
        severities: ["medium"],
        viewport_breakpoints: ["desktop"],
        metadata: {
          layoutVariant: "dense",
          ctaShown: true,
          regionSlug: "pacific-northwest",
          suggestionSummary: "Rain bands approaching; prep reallocation.",
          regionSummary: "Rain bands approaching; prep reallocation.",
          tenantMode: "demo",
          guardrailStatus: "healthy",
          criticalAlertCount: 1,
          signature: "Pacific Northwest|Monitoring heavy rain bands.|2025-05-02T08:00:00Z|1|1",
        },
      },
    ],
    context_tags: ["demo", "fallback"],
    context_warnings: [],
  };
}
